apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-mock
  labels:
    app: commerce-mock
spec:
  selector:
    matchLabels:
      app: commerce-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: commerce-mock
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/xf-application-mocks/commerce-mock:latest
        imagePullPolicy: Always
        name: commerce-mock
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
        - name: RENEWCERT_JOB_CRON
          value: "00 00 1 * * *"
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
            
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-mock
  labels:
    app: commerce-mock
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: commerce-mock
