apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: c4c-mock
  labels:
    app: c4c-mock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c4c-mock
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/xf-application-mocks/c4c-mock:latest
        imagePullPolicy: Always
        name: c4c-mock
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: c4c-mock
  labels:
    app: c4c-mock
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: c4c-mock
