apiVersion: apps/v1
kind: Deployment
metadata:
  name: c4c-mock
  labels:
    app: c4c-mock
spec:
  selector:
    matchLabels:
      app: c4c-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: c4c-mock
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/xf-application-mocks/c4c-mock:latest
        imagePullPolicy: Always
        name: c4c-mock
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: c4c-mock
  labels:
    app: c4c-mock
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: c4c-mock
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    app: c4c-mock
  name: c4c-mock
spec:
  hostname: c4c
  service:
    name: c4c-mock
    port: 10000